name: unipus_iwrite
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  intl: ^0.17.0
  dio: ^4.0.4
  json_annotation: ^4.4.0
  flutter_screenutil:
  shared_preferences: ^2.0.11
  flutter_svg: ^1.0.0
  fluttertoast: ^8.0.8
  device_info: ^2.0.3
#  provider: ^6.0.1
  package_info: ^2.0.2
  flutter_spinkit: ^5.1.0
  url_launcher: ^6.0.16
  cached_network_image: ^3.2.0
  html: ^0.15.0
  palette_generator: ^0.3.2
  flutter_swiper_null_safety: ^1.0.2
  #网络状态
  connectivity: ^3.0.6
  logger: ^1.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  webview_flutter: ^3.0.0
#  fluro: ^2.0.3
  page_transition: ^2.0.4
  dots_indicator: ^2.0.0
  sso_flutter:
#    git:
#      url: git@gitlab.nse.cn:organ/flutterTeam/sso.git
#      ref: dev
    path: ../sso_flutter


  animations: ^2.0.2
  get: ^4.6.1
#下拉刷新
  pull_to_refresh: ^2.0.0
#相机
  camera:
    path: camera-0.9.4+7
  path_provider: ^2.0.8
#  flutter_test from sdk depends on path 1.8.0
#  path: ^1.8.1
  image_editor: ^1.0.2
  qiniu_flutter_sdk: ^0.3.0
  permission_handler: ^8.3.0


  #键盘上浮num：https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.5

#键盘监听 https://github.com/MisterJimson/flutter_keyboard_visibility
  flutter_keyboard_visibility: ^5.1.0

  uuid: ^3.0.5

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  json_serializable: ^6.1.1
  flutter_lints: ^1.0.4
  build_runner:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  ios: true
  android: true
  image_path_ios: 'icon/ios.png'
  image_path_android: 'icon/android.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'icon/adaptive.png'

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  assets:
    - assets/images/alert_right.png
    - assets/images/camera_bottom.png
    - assets/images/camera_flashlight.png
    - assets/images/camera_photograph.png
    - assets/images/camera_rotate.png
    - assets/images/camera_save.png
    - assets/images/camera_close.png
    - assets/images/cr_?.png
    - assets/images/grey_star.png
    - assets/images/heart_large.png
    - assets/images/heart_small.png
    - assets/images/ic_down_arrow.png
    - assets/images/ic_finger.png
    - assets/images/ic_finger_circle.png
    - assets/images/ic_home_clock.png
    - assets/images/ic_home_pencil.png
    - assets/images/ic_photo.png
    - assets/images/ic_photo_bg.png
    - assets/images/mine_arrow.png
    - assets/images/mine_bg.png
    - assets/images/mine_feedback.png
    - assets/images/mine_item_bg.png
    - assets/images/mine_set.png
    - assets/images/progress_bg.png
    - assets/images/result_guide_0.png
    - assets/images/result_guide_1.png
    - assets/images/result_guide_2.png
    - assets/images/result_select.png
    - assets/images/result_unselect.png
    - assets/images/scan_line.png
    - assets/images/stimulate_alert.png
    - assets/images/yellow_star.png
    - assets/images/ic_finger_circle.png
    - assets/images/ic_finger.png
    - assets/images/identity_common.png
    - assets/images/identity_junior.png
    - assets/images/identity_senior.png
    - assets/images/network_error.png
    - assets/images/sug_thumbup.png
    - assets/images/mine_icon.png
    - assets/images/record_empty.png
    - assets/images/correct_arrow.png
